name: Python Build CI

on:
  workflow_dispatch:

jobs:
  build:
    name: [Run] Python Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python_version: 3.8
      - name: Install Dependencies
        run: pip -r install requirements.txt
      - name: Run Tests
        run: echo "This is a test that actions worked."
